from alembic import op
import sqlalchemy as sa
"""autogen"""
revision = '8a5c8570ee1a'
down_revision = '0005_directory_integrity'
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('groups_name_key', 'groups', type_='unique')
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=True)
    op.drop_index('uq_lesson_notes_schedule_date', table_name='lesson_notes')
    op.create_unique_constraint('uq_lesson_notes_schedule_date', 'lesson_notes', ['schedule_id', 'note_date'])
    op.create_index(op.f('ix_lesson_notes_note_date'), 'lesson_notes', ['note_date'], unique=False)
    op.create_index(op.f('ix_lesson_notes_schedule_id'), 'lesson_notes', ['schedule_id'], unique=False)
    op.alter_column('rooms', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_unique_constraint(None, 'rooms', ['name'])
    op.add_column('schedule', sa.Column('second_teacher_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_schedule_day_of_week'), 'schedule', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_schedule_group_id'), 'schedule', ['group_id'], unique=False)
    op.create_foreign_key(None, 'schedule', 'teachers', ['second_teacher_id'], ['id'])
    op.create_unique_constraint(None, 'subjects', ['name'])
    op.add_column('teachers', sa.Column('room_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_teachers_name'), 'teachers', ['name'], unique=False)
    op.create_foreign_key(None, 'teachers', 'rooms', ['room_id'], ['id'])
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.drop_index(op.f('ix_teachers_name'), table_name='teachers')
    op.drop_column('teachers', 'room_id')
    op.drop_constraint(None, 'subjects', type_='unique')
    op.drop_constraint(None, 'schedule', type_='foreignkey')
    op.drop_index(op.f('ix_schedule_group_id'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_day_of_week'), table_name='schedule')
    op.drop_column('schedule', 'second_teacher_id')
    op.drop_constraint(None, 'rooms', type_='unique')
    op.alter_column('rooms', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_lesson_notes_schedule_id'), table_name='lesson_notes')
    op.drop_index(op.f('ix_lesson_notes_note_date'), table_name='lesson_notes')
    op.drop_constraint('uq_lesson_notes_schedule_date', 'lesson_notes', type_='unique')
    op.create_index('uq_lesson_notes_schedule_date', 'lesson_notes', ['schedule_id', 'note_date'], unique=True)
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.create_unique_constraint('groups_name_key', 'groups', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
