"""add composite indexes on schedule

Revision ID: a2f7c9eb05d9
Revises: a1f6b8ea04c9
Create Date: 2026-09-22 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a2f7c9eb05d9'
down_revision = 'a1f6b8ea04c9'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_schedule_group_day', 'schedule', ['group_id', 'day_of_week'], unique=False)
    op.create_index('ix_schedule_teacher_day', 'schedule', ['teacher_id', 'day_of_week'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_schedule_teacher_day', table_name='schedule')
    op.drop_index('ix_schedule_group_day', table_name='schedule')
    # ### end Alembic commands ###
